// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kspbnrvrhyhikjdsocvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzcGJucnZyaHloaWtqZHNvY3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTU3NjUsImV4cCI6MjA2MTM3MTc2NX0.ZdE8vxLuIHu2YxFkH1emG1TakDCFc7HeVO1VQEoSEIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);